# Generated by Django 4.2.1 on 2023-06-06 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
        ('pago', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='id_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pago', to='cliente.cliente', verbose_name='Cliente'),
        ),
    ]
